#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Static-Analysis-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordSpezi/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordSpezi/.github/.github/workflows/swiftlint.yml@v2
  markdown_link_check:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
  breaking_changes:
    name: Diagnose Breaking Changes
    uses: StanfordSpezi/.github/.github/workflows/breaking-changes.yml@v2
    if: ${{ github.ref_name != 'main' }}
    with:
      runsonlabels: '["macOS", "self-hosted"]'
